[package]
name = "rust"
version = "0.1.0"
authors = ["Ivan Galakhov <igalakhov.nyc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "6.3.0"
tokio = { version = "0.3", features = ["full"] }